name: Feature Request
description: Suggest a new feature or enhancement for pg_ttl_index
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I need to...
        This would allow me to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to have..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: "I've tried... but it doesn't work because..."

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use of the extension
        - High - Significantly improves my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this require breaking changes to existing functionality?
      options:
        - "No - Fully backward compatible"
        - "Maybe - Might affect some edge cases"
        - "Yes - Would break existing functionality"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples of how you'd like to use this feature
      render: sql
      placeholder: |
        -- Example usage
        SELECT ttl_create_index('my_table', 'created_at', 3600, 
          new_option => 'value'
        );

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or links about the feature request
      placeholder: Add any other context...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions to ensure this hasn't been suggested before
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
